### ISSUE TITLE
Return custom error messages on required properties

### ISSUE THREAD

**Issue by tjramage** [BenZed/feathers-schema#1]
How do I change the validation message (or just improve the existing one) that is returned when an object fails to pass schema validation?

At the moment, all I get back from the server is `Validation failed`. For example, take the following `Car` schema:

```
const carSchema = new Schema({
    make: { type: String, required: true, trim: true },
    model: { type: String, required: true, trim: true },
    engineSize: { type: String, required: true, trim: true }
});
```

If I try to create a new Car object and leave off the `engineSize` property, I have no information to debug on other than `Validation failed`. How can I return more a descriptive error message to tell me specifically what part failed validation?

Would appreciate some help here... really like how lightweight this library is and don't want to move over to something else as I love how nicely it fits in with Feathers.

**Comment by BenZed** [comment]
error.message will always be 'Validation failed.'

What you're looking for is error.errors, which will be an object that has the same shape as the defined schema; any fields that failed validation will be in the object as a key, and it's value will be the error message.

So, with your example schema, your complete error object would look like this, assuming the .create() data was blank:
`{
    message: "Validation failed",
    errors: {
        make: "Required.",
        model: "Required.",
        engineSize: "Required."
    }
}`

Now, if you'd like to change the message from 'Required.' to something else, configure the schema like so:

`
const carSchema = new Schema({
    make: { type: String, trim: true, required: 'Must have a make.' },
    model: { type: String, trim: true, required: 'Must have a model.' },
    // or with a config object
    engineSize: { type: String, trim: true, required: { msg: 'Cannot be blank.' } }
})`

Which will return an error object like this:

`{
    message: "Validation failed",
    errors: {
        make: "Must have a make.",
        model: "Must have a model.",
        engineSize: "Cannot be blank."
    }
}`

Hope this helps! I'll make sure that this is clearer in the documentation.

**Comment by tjramage** [comment]
@BenZed – Amazing! That's _exactly_ what I wanted. Thanks so much for the detail there, really appreciate it.
