### ISSUE TITLE
Password field hashing is incompatible with current repopulation logic

### ISSUE THREAD

**Issue by alzab** [BenZed/feathers-schema#5]
I noticed while testing patching the user model in my project that for some strange reason length validation on the password field was failing when left undefined (too long). I traced the issue down some more, and it appears that the population logic in feathers-schema actually retrieves previously stored values. This poses an issue for passwords, since they are typically hashed, and so repopulating with the hashed value not only results in potentially breaking validators that are meant to act on the raw password, but also results in hashing the hash and storing that during a patch (thus the password becomes invalid).

This would naturally be an issue with any sort of non-idempotent processing that occurs to inputs, not just password hashing.

Curious to know if this is a known issue, or perhaps if I'm missing something that would prevent this from happening?

**Comment by BenZed** [comment]
I've come across this *exact* problem.

In the future, I'm imagining functionality whereby a schema could be provided *serialization* methods. Their primary purpose would be to allow conversions from custom types to/from primitives that can be stored in a database.

This functionality could also be used to **hash** / **unhash** passwords.

For the time being, I use multiple hooks. Consider the following user schema:
```js
const userSchema = new Schema({

  email: { type: String, required: true },

  // The database requires a string, and that's it.
  // By the time the value gets to the user schema hooks, it will be validated
  // and hashed.
  password: { type: String, required: true }

})
```
Then, a custom hook to validate a password before it gets hashed:
```js
import { Property } from 'feathers-schema'
import { BadRequest } from 'feathers-errors'

function validatePassword (length = 8) {

  // We can still take advantage of schema validation methods in custom cases
  // by using single properties.
  const passProp = new Property({
    type: String,
    length: [ '>=', length ],
    nospaces: true
  })

  return async hook => {

    // Using custom validation hooks is a good opportunity to do data checks
    // against things that don't show up in the schema. For example, passwords
    // are commonly compared against a 'confirm password' field.
    const { password, confirm } = hook.data

    // If the password wasn't supplied, (perhaps we're patching a user, but not
    // changing their password) we dont need to validate further.
    if (typeof password !== 'string') {
      // Caveat: hashPassword hook fails if password key is in data but is
      // not a string. This handles cases where the password might be in the 
      // data as null
      delete hook.data.password
      return hook
    }

    if (password !== confirm)
      throw new BadRequest('Password Mismatch', {
        errors: {
          password: 'Must match confirm field.'
        }
      })

    const error = await passProp.validate(password)
    if (error)
      throw new BadRequest('Password Invalid.', { errors: {
        password: error
      }})
  }
}
```

And your user service hooks would look something like this:
```js
import { hashPassword } from 'feathers-authentication-local/lib/hooks'

const arr = [
   validatePassword(),
   // placing the hashPassword method before the userSchema (and thus, populate hook)
   // prevents the previously hashed password from being re-hashed and thus made invalid.
   hashPassword(),
   ...userSchema.hooks
]

userService.hooks({
   before: {
       create: arr,
       patch: arr,
       update: arr
   }
})

```

**Comment by BenZed** [comment]
@alzab if this clears everything up, I'll close this. Let me know!

**Comment by alzab** [comment]
@BenZed apologies for the late reply! Yep this clears things up, thanks. I like the idea of making this more seamless with serialisation methods, but this definitely works for now.
